brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include('todos.urls'))
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,

)


urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path('create/', TodoListCreateView.as_view(), name='todo_list_create'),
    path("<int:pk>/edit/", TodoListUpdateView.as_view(), name='todo_list_update'),
    path("<int:pk>/delete/", TodoListDeleteView.as_view(), name="todo_list_delete"),
    path('items/create/', TodoItemCreateView.as_view(), name='todo_item_create'),
    path('items/<int:pk>/edit/', TodoItemUpdateView.as_view(), name='todo_item_update')
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(TodoList, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from todos.models import TodoList, TodoItem

# Create your views here.


class TodoListListView(ListView):
    model = TodoList
    template_name = 'todos/list.html'


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = 'todos/detail.html'


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = 'todos/create.html'
    fields = ['name']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = 'todos/update.html'
    fields = ['name']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = 'todos/delete.html'
    success_url = reverse_lazy('todo_list_list')


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = 'items/create.html'
    fields = ['task', 'due_date', 'is_completed', 'list']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = 'items/update.html'
    fields = ['task', 'due_date', 'is_completed', 'list']

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.list.id])

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo List</title>
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

todos/templates/items/create.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Create a New Item</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>

{% endblock content %} {% comment %}
<p>
  <label for="task">Task:</label>
  <input type="text" id="task" name="task" />
</p>
<p>
  <label for="date">Due Date:</label>
  <input type="date" id="date" name="date" />
</p>
<p>
  <label for="completed">Is completed:</label>
  <input type="checkbox" id="completed" name="completed" />
</p>
<p>
  <label for="select">List:</label>
  <select name="select" id="select">
    {% for todolist in todolist_list %}
    <option value="{{ todolist.id }}">{{ todolist.name }}</option>
    {% endfor %}
  </select>
</p>
{% endcomment %}

todos/templates/items/update.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Update Item</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Update</button>
    </form>
  </div>
</main>

{% endblock content %}

todos/templates/todos/create.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Create a New List</h1>
    <form method="post">
      {% csrf_token %}
      <label for="name">List Name</label>
      <input type="text" id="name" name="name" />
      <button>Create</button>
    </form>
  </div>
</main>

{% endblock content %}

todos/templates/todos/delete.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Are you sure you want to delete "{{todolist}}"?</h1>
    <form method="post">
      {% csrf_token %}
      <button>Delete</button>
    </form>
  </div>
</main>

{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>{{todolist.name}}</h1>
    <p>
      <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
    </p>
    <p>
      <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
    </p>
    <h2>Tasks</h2>
    <table>
      <thead>
        <tr>
            <th>Task</th>
            <th>Due Date</th>
        </tr>
        <tbody>
            {% for item in todolist.items.all %}
            <tr>
                <td>
                 <a href="{% url 'todo_item_update' item.id %}">{{item.task}}</a>
                </td>
                <td>{{item.due_date}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </thead>
    </table>
  </div>
</main>

{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>My Lists</h1>
    <p>
      <a href="{% url 'todo_list_create' %}">Create a New List</a>
    </p>
    <p>
      <a href="{% url 'todo_item_create' %}">Create a New Task</a>
    </p>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Number of Items</th>
        </tr>
      </thead>
      <tbody>
        {% for todolist in todolist_list %}
        <tr>
          <td>
            <a href="{% url 'todo_list_detail' todolist.pk %}"
              >{{todolist.name}}</a
            >
          </td>
          <td>{{ todolist.items.all | length }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>

{% endblock content %}

todos/templates/todos/update.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Update List</h1>
    <form method="post">
      {% csrf_token %}
      <label for="name">List Name</label>
      <input type="text" id="name" name="name" />
      <button>Update</button>
    </form>
  </div>
</main>

{% endblock content %}